# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
# relative_permalinks: true

# Setup
title: Froyo Dai
tagline: "Media"
description: "UX Designer"
baseurl: /

author:
  name: "Froyo Dai"

paginate: 5

# Custom vars
version: 2.1.0
